# docker-compose.yml
version: '3.8' # Docker Compose 파일 형식 버전

services:
  backend:
    build: ./backend # backend 폴더의 Dockerfile을 사용하여 이미지 빌드
    ports:
      - "8000:8000" # 호스트의 8000번 포트를 컨테이너의 8000번 포트에 매핑
    volumes:
      - ./backend:/app # 호스트의 ./backend 폴더를 컨테이너의 /app에 마운트 (코드 변경 시 자동 반영)
    environment:
      # FastAPI에서 개발 모드를 활성화하려면 아래를 추가할 수 있습니다.
      PYTHONUNBUFFERED: 1
      UVICORN_RELOAD: "true"
      # 하지만 Docker Compose에서 volume 마운트를 통해 코드 변경을 바로 반영하므로 필수는 아닙니다.
      # 여기서는 명시적인 환경 변수는 넣지 않았습니다.

  frontend:
    build: ./frontend # frontend 폴더의 Dockerfile을 사용하여 이미지 빌드
    ports:
      - "3000:3000" # 호스트의 3000번 포트를 컨테이너의 3000번 포트에 매핑
    volumes:
      - ./frontend:/app # 호스트의 ./frontend 폴더를 컨테이너의 /app에 마운트
      - /app/node_modules # node_modules는 호스트에 마운트하지 않고 컨테이너 내부에 유지 (성능 향상)
    environment:
      # React 앱이 백엔드 API를 찾을 수 있도록 환경 변수 설정
      # React 개발 서버는 CORS 미들웨어가 필요합니다.
      # 이는 development 환경에서만 필요하며, production 빌드 시에는 다르게 처리됩니다.
      DANGEROUSLY_DISABLE_HOST_CHECK: "true" # 개발 서버에서 호스트 체크 비활성화 (Docker 사용 시 유용)
    depends_on:
      - backend # frontend 서비스가 시작되기 전에 backend 서비스가 시작되도록 종속성 설정