# docker-compose.yml
version: '3.8' # Docker Compose 파일 형식 버전

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000" # 호스트의 8000번 포트를 컨테이너의 8000번 포트에 매핑
    volumes:
      - ./backend:/app # 호스트의 ./backend 폴더를 컨테이너의 /app에 마운트 (코드 변경 시 자동 반영)
    environment:
      PYTHONUNBUFFERED: 1
      UVICORN_RELOAD: "true"


  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # 호스트의 3000번 포트를 컨테이너의 3000번 포트에 매핑
    volumes:
      - ./frontend:/app # 호스트의 ./frontend 폴더를 컨테이너의 /app에 마운트
      - /app/node_modules # node_modules는 호스트에 마운트하지 않고 컨테이너 내부에 유지 (성능 향상)
    environment:
      DANGEROUSLY_DISABLE_HOST_CHECK: "true" # 개발 서버에서 호스트 체크 비활성화 (Docker 사용 시 유용)
    depends_on:
      - backend # frontend 서비스가 시작되기 전에 backend 서비스가 시작되도록 종속성 설정